feat: Adiciona pestaña con gráfica de costo medio
FundacionAIS/aisalud pull request #74
Opened 2021-08-05 20:40 UTC by ainsu23

Resolves #71

2021-08-07 22:01 UTC, andyquinterom requested changes
Muy bien. Dado que esto tiene que quedar un poco pronto. Haré las correcciones y quedarán en mi rama B71.

2021-08-07 22:01 UTC, andyquinterom commented on modules/seguimiento.R
> +    })
se podria simplificar esto un poco

2021-08-07 23:40 UTC, andyquinterom commented
Este código es disfuncional. No funciona al correrse

2021-08-08 19:09 UTC, ainsu23 commented
Cambios realizados a excepción de simplificar df con función de gráfica.

2021-08-10 14:24 UTC, merged